trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

container:
  image: osrf/ros:crystal-desktop
  options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"

steps:
  - script: |
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
    displayName: Set up sudo
  - script: sudo apt-get update && sudo apt-get install -y ros-crystal-osrf-testing-tools-cpp default-jre
    displayName: Install APT dependencies
  - script: sudo apt-get install -y python3-colcon-common-extensions
    displayName: Install colcon
  - script: rosdep update && rosdep install -y --from performance_test --ignore-src
    displayName: Install ROS dependencies
  - script: |
      source /opt/ros/crystal/setup.bash && \
      colcon build \
        --merge-install \
        --cmake-args \
          -DCMAKE_BUILD_TYPE=Release \
        --base-path performance_test
    displayName: Build performance_test
  - script: |
      source /opt/ros/crystal/setup.bash && \
      colcon test \
        --merge-install \
        --base-path performance_test && \
      colcon test-result --verbose
    displayName: Test performance_test

